export const MALAYSIA_CITIES = [
  "Alor Setar",
  "Arau",
  "Batu Pahat",
  "Bintulu",
  "Bukit Mertajam",
  "Butterworth",
  "Cyberjaya",
  "George Town",
  "Ipoh",
  "Johor Bahru",
  "Kajang",
  "Kangar",
  "Kemaman",
  "Keningau",
  "Klang",
  "Kluang",
  "Kota Bharu",
  "Kota Kinabalu",
  "Kota Tinggi",
  "Kuala Kangsar",
  "Kuala Lumpur",
  "Kuala Terengganu",
  "Kuantan",
  "Kulim",
  "Kuching",
  "Labuan",
  "Lahad Datu",
  "Langkawi",
  "Manjung",
  "Melaka",
  "Miri",
  "Muar",
  "Nilai",
  "Pasir Gudang",
  "Petaling Jaya",
  "Port Dickson",
  "Putrajaya",
  "Sandakan",
  "Segamat",
  "Sekinchan",
  "Senai",
  "Sepang",
  "Seremban",
  "Shah Alam",
  "Sibu",
  "Simpang Empat",
  "Sungai Petani",
  "Taiping",
  "Tawau",
  "Teluk Intan",
  "Temerloh",
  "Ulu Tiram",
];
